version: '3.2'

services:
  ui:
    build:
      context: .
      target: local-dev
      dockerfile: Dockerfile
    labels:
      lagoon.type: none
    command: yarn run dev
    volumes:
      - ./src:/app/src
      - ./.env.defaults:/app/.env.defaults
      - ./.env.schema:/app/.env.schema
      - ./package.json:/app/package.json
    ports:
      - '3003:3003'
    networks:
      - default
    environment:
      LAGOON_ROUTE: http://lagoon-ui.docker.amazee.io
      LAGOON_UI_TOURS_ENABLED: true
      NODE_ENV: development
      GRAPHQL_API: "${GRAPHQL_API:-http://0.0.0.0:3000/graphql}"
      KEYCLOAK_API: "${KEYCLOAK_API:-http://0.0.0.0:8088/auth}"

